GRANT CONNECT ON DATABASE task_db TO task_user;
GRANT USAGE ON SCHEMA public TO task_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO task_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO task_user;
GRANT CREATE ON SCHEMA public TO task_user;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO task_user;


select * from task_db;